# This is a basic workflow to help you get started with Actions

name: Slack notification

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
slackNotification:name: Slack Notificationruns-on: ubuntu-lateststeps:- run: echo ::set-env name=pull_number::$(jq — raw-output .pull_request.number $GITHUB_EVENT_PATH)- name: Slack Notificationuses: rtCamp/action-slack-notify@masterenv:SLACK_CHANNEL: YOUR_SLACK_CHANNEL_NAMESLACK_MESSAGE: ‘Please review on https://github.com/YOUR_PATH/YOUR_REPO_NAME/pull/${{ env.pull_number}}’SLACK_TITLE: ‘Pull request’SLACK_USERNAME: ‘Gittan’SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
